/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 room.gltf --typescript 
*/

import React from 'react'
import { useGLTF, OrthographicCamera } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/room.gltf')
  return (
    <group {...props} dispose={null}>
      <pointLight intensity={113557.508} decay={2} color="#fffaed" position={[0, 12.825, 0]} rotation={[-Math.PI / 2, 0, 0]} />
      <OrthographicCamera makeDefault={false} far={1000} near={0.1} position={[9.985, 11.939, 9.892]} rotation={[-0.527, 0.786, 0.39]} />
      <mesh geometry={nodes.room.geometry} material={materials.room} scale={10} />
      <mesh geometry={nodes.bed.geometry} material={materials.bed} position={[-2.167, 1, 5.882]} scale={[7.144, 1, 3.211]} />
      <mesh geometry={nodes.desk.geometry} material={materials.desk} position={[-7.785, 1, -4.478]} scale={[1.84, 1, 1]} />
      <mesh geometry={nodes.screen.geometry} material={materials.screen} position={[-9.254, 5.316, -6]} scale={[0.134, 0.912, 1.462]} />
    </group>
  )
}

useGLTF.preload('/room.gltf')
