/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 room.gltf --types 
*/

import { OrthographicCamera, useAnimations, useGLTF } from "@react-three/drei";
import React from "react";
import type * as THREE from "three";
import type { GLTF } from "three-stdlib";

type ActionName = "screenAction.001" | "camMove";

interface GLTFAction extends THREE.AnimationClip {
	name: ActionName;
}

type GLTFResult = GLTF & {
	nodes: {
		room: THREE.Mesh;
		bed: THREE.Mesh;
		desk: THREE.Mesh;
		screen: THREE.Mesh;
	};
	materials: {
		room: THREE.MeshStandardMaterial;
		bed: THREE.MeshStandardMaterial;
		desk: THREE.MeshStandardMaterial;
		screen: THREE.MeshPhysicalMaterial;
	};
	animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
	const group = React.useRef<THREE.Group>();
	const { nodes, materials, animations } = useGLTF("/room.gltf") as GLTFResult;
	const { actions } = useAnimations(animations, group);
	return (
		<group ref={group} {...props} dispose={null}>
			<group name="Scene">
				<group
					name="area"
					position={[-9.146, 5.316, -6]}
					rotation={[-Math.PI / 2, -1.571, 0]}
					scale={[1.597, 2.574, 1.597]}
				/>
				<group
					name="areatwo"
					position={[-13.776, 5.316, 0.815]}
					rotation={[-0.598, -1.257, 0.996]}
					scale={10}
				/>
				<pointLight
					name="pointone"
					intensity={113557.508}
					decay={2}
					color="#fffaed"
					position={[0, 12.825, 0]}
					rotation={[-Math.PI / 2, 0, 0]}
				/>
				<OrthographicCamera
					name="camera"
					makeDefault={false}
					far={1000}
					near={0.001}
					position={[9.985, 11.939, 9.892]}
					rotation={[-0.527, 0.786, 0.39]}
				/>
				<mesh
					name="room"
					geometry={nodes.room.geometry}
					material={materials.room}
					scale={10}
				/>
				<mesh
					name="bed"
					geometry={nodes.bed.geometry}
					material={materials.bed}
					position={[-2.167, 1, 5.882]}
					scale={[7.144, 1, 3.211]}
				/>
				<mesh
					name="desk"
					geometry={nodes.desk.geometry}
					material={materials.desk}
					position={[-7.785, 1, -4.478]}
					scale={[1.84, 1, 1]}
				/>
				<mesh
					name="screen"
					geometry={nodes.screen.geometry}
					material={materials.screen}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("/room.gltf");
